		<div id="title_menu">
			<div id="page_title"><?php echo $page_title; ?></div>
		</div>
		<div id="content">
			<div id="product-add">
				<h5>Page Information</h5>
				<ul class="ui-tabs-nav">
                    <li><a href="#general"><span>Content</span></a></li>
					<li><a href="#meta"><span>Meta data</span></a></li>
                </ul>
				<form id="super_form" name="super_form" method="post" action="<?php echo site_url(url::current()); ?>">
				<div id="general">
                    <!-- General Validation Error -->
					<?php if(isset($errors)){ foreach($errors as $error){ echo '<div class="error-ex">'. $errors. '</div>'; } } ?>
					<!-- General Validation Error -->
					<p>
                        <label for="type">Type</label>
                        <select id="type" name="type">
							<?php foreach(Config::item('cms.page_type') as $key => $status){ ?>
							<option value="<?php echo $key; ?>" <?php if(!(strcmp($key, (isset($repopulate->type)) ? $repopulate->type : $page->type))){echo "selected=\"selected\"";} ?>><?php echo $status;?></option>
							<?php } ?>
						</select>
                    </p>
					<p>
                        <label for="title">Title</label>
                        <input id="title" name="title" type="text" value="<?php echo ($repopulate->title)?$repopulate->title : $page->title;?>" size="25" class="input_size" />
                        <input id="order" name="order" type="hidden" value="<?php echo $page->order; ?>" />
                    </p>
                    <p>
                        <label for="url">Slug</label>
                        <input id="url" name="url" type="text" value="<?php echo ($repopulate->url)?$repopulate->url : $page->slug;?>" size="25" class="input_size" />
                    </p>
					<p>
						<label for="status">Status</label>
						<select id="status" name="status">
							<?php foreach(Config::item('cms.page_status') as $key => $status){ ?>
							<option value="<?php echo $key; ?>" <?php if(!(strcmp($key, (isset($repopulate->status)) ? $repopulate->status : $page->status))){echo "selected=\"selected\"";} ?>><?php echo $status;?></option>
							<?php } ?>
						</select>
					</p>
					<p>
                        <label for="group">User Group</label>
                        <select name="group" id="group">
                            <option value="0" "selected="selected">None</option>
                        <?php foreach ($roles as $role) { ?>
                            <option value="<?php echo $role->id; ?>" <?php if (!(strcmp($role->id, (isset($repopulate->group)) ? $repopulate->group : $page->access))) echo "selected=\"selected\""; ?>><?php echo ucfirst($role->name); ?></option>
                        <?php } ?>
                        </select>
                    </p>
                    <p>
                        <label for="parent">Parent:</label>
                        <select name="parent" id="parent">
                            <option value="0" <?php if (!(strcmp($parent_id,0))) echo "selected=\"selected\""; ?>>None</option>
                        <?php foreach ($parent as $head) { ?>
                            <option value="<?php echo $head->id; ?>" <?php if (!(strcmp($head->id, (isset($repopulate->parent)) ? $repopulate->parent : $page->parent))) echo "selected=\"selected\""; ?>><?php echo $head->title; ?></option>
                        <?php } ?>
                        </select>
                    </p>                   
					<p>
                        <label for="menu">Show in Menu</label>
                        <input id="menu" name="menu" type="checkbox" value="1" <?php if (!(strcmp(1, (isset($repopulate->menu)) ? $repopulate->menu : $page->menu_show))) echo "checked=\"checked\""; ?> />
                    </p>
					<p>
                        <label for="body">Body</label>
                        <textarea id="body" name="body" rows="8" cols="20"><?php echo (isset($repopulate->body)) ? $repopulate->body : $page->body;?></textarea>
                    </p>
				</div>
				<div id="meta">
                    <h4>Meta data</h4>
					<p>
                        <label for="keywords">Keywords</label>
                        <input id="keywords" name="keywords" type="text" value="<?php echo(isset($repopulate->keywords)) ? $repopulate->keywords : $page->meta_key; ?>" size="25" class="input_size" />
                    </p>
					<p>
                        <label for="description">Description</label>
                        <textarea id="description" name="description" rows="2" class="input_size"><?php echo(isset($repopulate->description)) ? $repopulate->description : $page->meta_desc; ?></textarea>
                    </p>
				</div>
				<div class="form_button">
					<input value="Update Page" type="submit" class="submit_button" />
				</div>
				</form>
			</div>
	  	</div>