        <div id="title_menu">
			<div id="page_title"><?php echo $page_title; ?></div>
		</div>
		<div id="content">
            <form id="template-form" class="smart-form" name="template" method="post" action="<?php site_url('admin/layout/add'); ?>">
				<p>
					<label for="name">Name:</label>
					<input type="text" id="name" name="name" value="<?php echo $repopulate['name']; ?>" class="size" />
				</p>
				<?php if(isset($errors['name'])) echo '<div class="error">' . $errors['name'] . '</div>'; ?>
				<p>
					<label for="file">File:</label>
					<input type="text" id="file" name="file" value="<?php echo $repopulate['file']; ?>" class="size" />
				</p>
				<?php if(isset($errors['file'])) echo '<div class="error">' . $errors['file'] . '</div>'; ?>
				<div class="form-button">
					<input type="submit" name="submit" value="Add" class="submit" />
				</div>
            </form>
        </div>
