		<div id="title_menu">
			<div id="page_title"><?php echo $page_title; ?></div>
		</div>
		<div id="main">
			<div id="content-wrapper">
				<div id="content">
					<?php if($message) echo '<div id="message">'. $message .'</div>'; ?>
					<form id="template-form" class="smart-form" name="template" method="post" action="<?php echo site_url('admin/add_property'); ?>">
						<p>
							<label for="variable">Variable:</label>
							<input type="text" id="variable" name="variable" class="size" />
						</p>
		                <p>
							<label for="name">Name:</label>
							<input type="text" id="name" name="name" class="size" />
						</p>
						<p>
							<label for="type">Type:</label>
							<select id="type" name="type" class="size">
								<option value="text">Text</option>
								<option value="textarea">Textarea</option>
								<option value="select">Select</option>
		                        <option value="checkbox">Checkbox</option>
		                        <option value="radio">Radio</option>
		                        <option value="file">File</option>
							</select>
						</p>
		                <p>
		                    <label for="value">Default Value:</label>
		                    <input type="text" id="value" name="value" value="" class="size" />
		                </p>
						<div class="form-button">
							<input type="submit" name="submit" value="Add" class="submit" />
						</div>
		            </form>
				</div>
			</div>

			<div id="sidebar-wrapper">
				<div id="sidebar">
					<div id="add"><a href="<?php echo site_url('admin/layout/new'); ?>"><span>Add</span></a></div>
					
				</div>
			</div>
		</div>