		<div id="title_menu">
			<div id="page_title"><?php echo $page_title; ?></div>
		</div>
		<div id="main">
			<div id="content-wrapper">
				<div id="content">
					<?php if($message) echo '<div id="message">'. $message .'</div>'; ?>
					<?php if($delete_confirm) echo '<div id="delete_confirm">'. $delete_confirm .'</div>'; ?>
					<table class="data-grid">
						<tr class="row row-0">
							<th class="col col-0">Name</th>
							<th class="col col-1">Type</th>
							<th class="col col-2">Modify</th>
						</tr>
						<?php if(count($layouts) > 0) { $i = 1; ?>
							<?php
								foreach ($layouts as $layout) {
									$row = ($i % 2 != 0) ? 'row row-1' : 'alt';
									$i++;
							?>
								<tr class="<?php echo $row; ?>">
									<td class="col col-0"><?php echo $layout->name; ?></td>
									<td class="col col-1"><?php echo $layout->type; ?></td>
									<td class="col col-2">
										<a href="<?php echo site_url('admin/layout/edit/'.$layout->id); ?>">Edit</a> |
										<a href="<?php echo site_url('admin/layout/property/'.$layout->id); ?>">Property</a> |
										<a href="<?php echo site_url('admin/layout/del/'.$layout->id); ?>">Delete</a>
									</td>
								</tr>
						<?php } ?>
					<?php } ?>
					</table>
				</div>
			</div>

			<div id="sidebar-wrapper">
				<div id="sidebar">
					<div id="add"><a href="<?php echo site_url('admin/layout/new'); ?>"><span>Add</span></a></div>
					<div id="uploader" <?php if(!$add) echo 'class="hide"'; ?>>
						<form id="popup-add" class="smart_form" enctype="multipart/form-data" method="post" action="<?php echo site_url('admin/layout/add'); ?>">
							<p>
								<label for="name">Name</label><?php echo $add; ?>
								<input id="name" name="name" type="text" value="<?php echo $repopulate['name']; ?>" class="size" />
								<?php if(isset($errors['name'])) echo '<span class="error">' . $errors['name'] . '</span>'; ?>
							</p>
							<p>
								<label for="type">Type</label>
								<select id="type" name="type" class="size">
									<option value="page">Page</option>
									<option value="gallery">Gallery</option>
									<option value="blog">Blog</option>
								</select>
							</p>
							<p>
								<label for="frontend">Frontend</label>
								<select id="frontend" name="frontend" class="size">
									<option value="yes" selected="selected">Yes</option>
									<option value="no">No</option>
								</select>
							</p>
							<div class="submit">
								<input type="submit" name="submit" value="Add" class="submit-button" />
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>