<?php foreach ($children as $child) { ?>
<tr id="<?php echo $child['id']; ?>" class="product">
	<td class="label pad node level-<?php echo $level; if(!$child['has_children']) echo ' no-children'; else if($child['is_expanded']) echo ' children-visible'; else echo ' children-hidden'; ?>">
		<div class="page" style="padding-left: 4px;">
			<span class="w1">
				<?php if($child['has_children']){ ?>
					<?php echo html::image(array('src'=>'cms_assets/images/spacer.gif', 'alt'=>'Spacer', 'width' => '17', 'height'=>'17', 'align'=>'middle', 'class'=>'expander', 'id'=>$child['id'])); ?>
				<?php } ?>
				<a href="<?php echo site_url('admin/page/subpage/'.$child['id']); ?>">
					<?php echo html::image(array('src'=>'cms_assets/images/page.png', 'alt'=>'Page', 'width' => '32', 'height'=>'32', 'align'=>'middle')); ?>
					<span class="title"><?php echo $child['title']; ?></span>
				</a>
				<?php echo html::image(array('src'=>'cms_assets/images/drag.gif', 'alt'=>'Drag and Drop', 'align'=>'middle', 'class'=>'drag')) ?>
			</span>
		</div>
	</td>
	<td class="quantity pad"><a href="<?php echo site_url($child['slug']); ?>"><?php echo site_url($child['slug']); ?></a></td>
	<td class="price pad"><?php echo ($child['menu_show'] == 0)?'No':'Yes'; ?></td>
	<td class="status pad published-status"><?php echo extend::status($child['status']); ?></td>
	<td class="modify pad">
		<a href="<?php echo site_url('admin/page/create/'.$child['id']); ?>">
			<?php echo html::image(array('src'=>'cms_assets/images/create.png', 'alt'=>'Add', 'width' => '16', 'height'=>'16', 'align'=>'middle')); ?>
		</a>
		<a href="<?php echo site_url('admin/page/edit/'.$child['id']); ?>">
			<?php echo html::image(array('src'=>'cms_assets/images/pencil.png', 'alt'=>'Edit', 'width' => '16', 'height'=>'16', 'align'=>'middle')); ?>
		</a>
		<a href="<?php echo site_url('admin/page/delete/'.$child['id']); ?>">
			<?php echo html::image(array('src'=>'cms_assets/images/delete.png', 'alt'=>'Delete', 'width' => '16', 'height'=>'16', 'align'=>'middle')); ?>
		</a>
	</td>
	<?php //if($child['has_children']) $this->children($child['id'], $level); ?>
</tr>
<?php } ?>